#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidApplication3.Resource", IsApplication=true)]

namespace AndroidApplication3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int Email = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int EmailText = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int FIO = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int FIOText = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int Faculty = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int FacultyText = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int Gender = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int GenderText = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int Group = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int GroupText = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int Password = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int PasswordText = 2131034118;
			
			// aapt resource value: 0x7f05000d
			public const int RefreshProfileButton = 2131034125;
			
			// aapt resource value: 0x7f050000
			public const int UserProfileButton = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Event = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int UserProfile = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int Email = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int FIO = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int Faculty = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int Gender = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int Group = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int Password = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int RefreshProfile = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int UpHeader = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int UserProfile = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
